### ISSUE TITLE
Many error and issues 

### ISSUE THREAD

**Issue by abdul-mannan-khan** [seifEddy/com2009_team00#1]
Thank you so much for sharing this work. It is really interesting particularly in terms of performance in C++. I am struggling to run and I found many errors in `Readme`. Instructions and commands mismatched. 

For example 

`roslaunch com2009_simulation task4.launch`

I also found errors in launching files. Particularly, there was nothing mentioned what kind of `frame` I need to choose to run the simulation successfully. I selected `base_link` as follows:
![Screenshot from 2024-08-13 10-47-13](https://github.com/user-attachments/assets/7d887084-317d-436f-90a2-6d44cdbfe79c)

still getting errors. Could you please suggest some solution? Thank you so much for your response.

**Comment by seifEddy** [comment]
Hey abdul-mannan-khan, 
I am glad you found this helpful. I stated in the readme file that you need to install tuos_ros package which includes the com2009_simulation launch files including the one we are interested in task4.launch which only starts the gazebo simulation and the not the navigation nor the exploration. You must install it and then compile it and after that you clone this repo so you can use this launch file (roslaunch com2009_team00 task4.launch target_colour:<desired-color>)

One more thing, you mentioned that you are interested in the C++ performance. The navigation as you know is implemented in C/C++, however, the rest of it is implemented in Python, but you can play around with the computer vision stuff to accelerate them even more using C++.

Please navigate this [link](https://drive.google.com/file/d/1PNroKepSyD_j1XWeaniO4mRM8ubKAGW9/view?usp=sharing) to see how it is supposed to be launched, and feel free to ask anything.

**Comment by abdul-mannan-khan** [comment]
Hi @seifEddy for your quick response. I have `tuos_ros` package in my folder as  you can see here
![Screenshot from 2024-08-13 14-13-15](https://github.com/user-attachments/assets/711fee0b-82cb-42e8-9bee-2b3d164ae103)

and it compiles successfully:

![Screenshot from 2024-08-13 14-13-25](https://github.com/user-attachments/assets/6e8d5808-39a1-47ad-a004-388186d7f4d0)

and I get the following error:

```
yyy@zzz:~/catkin_ws$ roslaunch com2009_simulation task4.launch
RLException: [task4.launch] is neither a launch file in package [com2009_simulation] nor is [com2009_simulation] a launch file name
The traceback for the exception was written to the log file
```
when I tried `roslaunch com2009_team00 task4.launch target_colour:"orange"`, I got 

```
roslaunch com2009_team00 task4.launch target_colour:"orange"
Usage: roslaunch [options] [package] <filename> [arg_name:=value...]
       roslaunch [options] <filename> [<filename>...] [arg_name:=value...]

If <filename> is a single dash ('-'), launch XML is read from standard input.

roslaunch: error: The following input files do not exist: target_colour:orange
```
I tried inputting arguments in "orange ", 'orange ' and `orange`. None of them worked and also without comman like **orange** and without argument for the command `roslaunch com2009_team00 task4.launch`, I get the following:

![Screenshot from 2024-08-13 14-25-05](https://github.com/user-attachments/assets/97a4cb73-4d9d-4926-ad3b-5be23ff12866)

Thank you so much for your help.

**Comment by seifEddy** [comment]
First of all, I _recommend_ building the packages in a separate clean workspace, and use catkin_make instead of catkin build. Even though you used catkin build, **you must source your workspace (try "source ~/catkin_ws/devel/setup.bash")** since based on what you've shared the launch file is not found at all. Furthermore, something you must consider is that the available and detectable target colors are red, green, blue and yellow. If you want to add another color you must modify the code a bit to include that. One last thing, when you want to specify the color use target_colour:=red for example and not target_colour:red (notice the equal sign).

**Comment by abdul-mannan-khan** [comment]
@seifEddy, with due respect.  I have already tried them. Sourcing is not an issue. The Linux machine is confugired to source ROS using . `.basrch` file using 

```
# Source ROS Noetic setup
source /opt/ros/noetic/setup.bash

# Source your Catkin workspace setup
source ~/catkin_ws/devel/setup.bash
```

You can also put them in your `.bashrc` file and you don't have to source your ROS again. 

Secondly, I am 100% sure that `catkin build` and `catkin_make` does not make any difference. Even then I followed your procedure and as expected the errors remain the same except the one you mentioned `target_colour:=red`, however, there was no difference in spawing the robot as shared in the previous screen shot.  

Please check your `Readme` file and ask someone to follow the process mentioned there if you think I am doing something wrong. It is not working. Thank you so much for all your efforts and help.

**Comment by seifEddy** [comment]
Based on what you provided, the issue is not coming from this package, in fact it is with the com2009_simulations task4.launch. which not mine. The package is not recognized as you saw 
`yyy@zzz:~/catkin_ws$ roslaunch com2009_simulation task4.launch
RLException: [task4.launch] is neither a launch file in package [com2009_simulation] nor is [com2009_simulation] a launch file name
The traceback for the exception was written to the log file` 
so basically there is something wrong with the setup of this package. This package is actually working for me and for some colleagues so I do not think that it has an issue like what the one your pointing at. Furthermore, try to set the environment variable  TURTLEBOT3_MODEL to waffle for example. 


NB: This error `yyy@zzz:~/catkin_ws$ roslaunch com2009_simulation task4.launch
RLException: [task4.launch] is neither a launch file in package [com2009_simulation] nor is [com2009_simulation] a launch file name
The traceback for the exception was written to the log file` means that either you do not have this package for real or you are trying to launch it from a terminal that does not recognize this ROS workspace.

**Comment by abdul-mannan-khan** [comment]
@seifEddy Your package name is`com2009_team00`. You are talking about `com2009_simulations`. Where is this package? Are you talking about `tuos_ros` package? This package works. Again, you need to check your `Readme` file.

**Comment by abdul-mannan-khan** [comment]
I managed to make it work. First of all, I changed this

```
roslaunch com2009_simulation task4.launch
```

into 

```
roslaunch com2009_simulations task1.launch
```

There is not `task4.launch` file and also it was `..._simulations` and not `..._simulation`. 

There was an error in the launch file (all). It was 

```
  <param name="robot_description" command="$(find xacro)/xacro.py $(find turtlebot3_description)/urdf/turtlebot3_$(arg model).urdf.xacro" />
``` 
`xary.py` is not required for ROS Noetic. So, I changed this into 

```
  <param name="robot_description" command="$(find xacro)/xacro $(find turtlebot3_description)/urdf/turtlebot3_$(arg model).urdf.xacro" />
```
After that, the command `roslaunch com2009_simulations task1.launch` works. 

Next, in a separate terminal, I run

```
roslaunch com2009_team00 task4.launch target_colour:=<desired color >
```
for example

```
roslaunch com2009_team00 task4.launch target_colour:=red
```
Then, fianlly in another terminal, 

```
rosservice call /move_service "request_signal: true" 
```
Dear @seifEddy, you can update your `Readme` and hopefully, it will be fine. Thank you for your repository.
